Added CODE_OF_CONDUCT.md and also updated README.md
bemusic/bemuse pull request #767
Opened 2022-10-16 18:31 UTC by sb-decoder

2022-10-16 18:48 UTC, dtinth requested changes

2022-10-16 18:48 UTC, dtinth commented on README.md
> +- Make a pull request! (compare your branch with the owner main branch)
While I appreciate the extra guidance (e.g. drop a star), we already have a developer guide on the website.

https://bemuse.ninja/project/docs/developer-guide.html

Let’s just link there instead. Feel free to make changes to the developers guide to make it easier for newcomers to work on the project.

2022-10-16 18:48 UTC, dtinth commented on CODE_OF_CONDUCT.md
> +# The Ruby Community Conduct Guideline
Just say “Conduct Guideline” here as this project is not related to Ruby.

2022-10-16 18:48 UTC, dtinth commented on CODE_OF_CONDUCT.md
> +### This document provides community guidelines for a safe, respectful, productive, and collaborative place for any person who is willing to contribute to the Ruby community. It applies to all “colla
These can be just a paragraph, no heading needed. Also replace "Ruby community" with "Bemuse project".

2022-10-16 18:48 UTC, dtinth commented on CODE_OF_CONDUCT.md
> +## We have picked the following conduct guideline based on an early proposed draft of the PostgreSQL CoC, for Ruby developers community for safe, productive collaboration.
This line is probably not needed because it is not relevant to Ruby.

2022-10-16 19:02 UTC, sb-decoder commented
@dtinth please check the changes and tell me if you want any further changes

2022-10-17 11:57 UTC, sb-decoder commented
@dtinth Please check this

2022-10-17 13:59 UTC, dtinth approved these changes
LGTM! Thanks 😃

2022-10-17 15:50 UTC, sb-decoder commented
Please merge this @dtinth

2022-10-17 16:11 UTC, dtinth commented
@sb-decoder In Bemuse project [we merge PRs when we are about to release a new version](https://bemuse.ninja/project/docs/workflows.html), so it will take a while. This PR should count on your Hacktoberfest dashboard now because I have given an approving review. Please check the dashboard.

2022-10-17 16:12 UTC, sb-decoder commented
Ok Thank you @dtinth

2022-10-17 18:56 UTC, merged